### ISSUE TITLE
Documenting the Project

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/category-captainship#1]
Let's change the readme file to include specifics about the project's motivations, details about Nielsen data, how we've gone about finding Supervalu, and anything else that might be relevant.

**Comment by cdbale** [comment]
@marcdotson @morganbale @samuelr6 @sophie-cee 
Jeff suggested that we begin writing portions of the actual paper documenting what we've done so far, in particular how the synthetic control method works. We have a couple of paragraphs that we've written already about the data cleaning process stored in the main google drive folder. We are considering moving those to github and combining them into one document. @marcdotson What type of document (.Rmd, .md, etc.) do we want to write the paper in? And should we keep it in the repo or drive?

**Comment by marcdotson** [comment]
@cdbale @morganbale @samuelr6 @sophie-cee Write it in R Markdown in the Paper folder as part of the repo:

> `/Paper` The manuscript of the paper, without any PDF knits.

It's probably easiest to use the README.Rmd file so it's the default thing you see in that folder if you are reviewing on GitHub. Consider what you should transfer from the README.Rmd that serves as the index page of the repo to the actual paper as well.

**Comment by cdbale** [comment]
Add documentation on the process of getting upc prefixes and how we assign manufacturers based on that.
