### ISSUE TITLE
Conform to Standard Project Organization

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/category-captainship#10]
Let's get on the same page as the new standard organization. See [ra-training](https://github.com/marcdotson/ra-training) for details.

**Comment by cdbale** [comment]
We're having issues because the lab computers we are using won't let us download and use Git normally. We're working on a workaround.

**Comment by marcdotson** [comment]
Are you just trying to clone to your personal accounts in the lab? That's gotta be a pain. Not something I actively considered. What workaround are you looking at, @cdbale?

**Comment by cdbale** [comment]
The computers allow us to download and install git to our personal folder but R can't find Git on the system filepath. Trying to figure out if we can point R to Git or if we can install it on the correct path. Is there anything on this in the initial Git and R setup in the RA training materials? @marcdotson

**Comment by marcdotson** [comment]
@cdbale I'd start with troubleshooting options in the initial setup and then see if there's anything else that might help in [Happy Git and GitHub for the userR](https://happygitwithr.com).

**Comment by marcdotson** [comment]
Finished with pull request #17.
