### ISSUE TITLE
Revisit Sales Tables

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#12]
Change the table code so that it only contains the UPCs that belong to the Captain, Validator, and Private Label instead of the top 100 selling UPCs in the category.

Reference the sheet in google drive showing the dates that CC was implemented once you start examining changes. The manufacturers that own each brand in each category can be found in a 'brand' file in each category on google drive.

Questions can be directed to @morganbale and @cdbale

**Comment by morganbale** [comment]
We are now using another method, see code for "synthetic retailer test".
