### ISSUE TITLE
Schedule summer meeting

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/category-captainship#16]
@cdbale @morganbale @samuelr6 @sophie-cee what would be a good time for you all to meet over the summer?

**Comment by morganbale** [comment]
@marcdotson @samuelr6 @sophie-cee Early Thursday afternoon would be great for Cameron and I, but we're open for other times.

**Comment by marcdotson** [comment]
What about 2 pm on Thursdays? That work for you, @jeff-dotson?

**Comment by samuelr6** [comment]
That works for me.

**Comment by sophie-cee** [comment]
Works for me as well.

**Comment by morganbale** [comment]
That works for us, are we meeting tomorrow?

**Comment by marcdotson** [comment]
Yes, let's meet tomorrow.
