### ISSUE TITLE
When to Specify Treatment?

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#18]
Since the data is on the weekly level, we can't choose a treatment date that exactly coincides with the target reset date. Should we pick the week identifier that is closest to the reset date or the week  identifier that occurs immediately after the target reset date? @jeff-dotson @marcdotson @morganbale @sophie-cee @samuelr6

**Comment by marcdotson** [comment]
This is an open question. We don't know if the actual reset date matches the schedule. It's probably safe to assume it's not prior to the scheduled date, but it could be within a number of weeks of the scheduled date.

Also, remember that while you should commit often, you shouldn't need to push your commits to GitHub very often -- maybe two or three times a day at most?

**Comment by marcdotson** [comment]
Really, though. @cdbale and @morganbale, don't push a single commit. Try and push once a day.

**Comment by cdbale** [comment]
Don't have a choice since we have to manually upload the files. We're also editing the code directly in Github.

**Comment by marcdotson** [comment]
Okay.
