### ISSUE TITLE
New Analysis of Retailers

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#28]
Do analysis of market share for Captain and Private Label at the store level.

Do analysis of average price for Captain and Private Label.

**Comment by cdbale** [comment]
Use wayback machine to view Supervalu website from 2012. Consider expansion to other locations, investigate zip code/county locations for the two chains owned by Supervalu in MN.

**Comment by cdbale** [comment]
Expand the RDiT to other categories in Minnesota. Use a heat chart on 1 store for retailer 221 in Minnesota in the cereal category. 2314183. Heat map should have a row for each upc, within each cell is unit sales. @morganbale @cdbale @sophie-cee

**Comment by morganbale** [comment]
1. Clean up issues

2. Bring evidence for choosing retailers (store #, etc)

3. List of covariates at store and retailer level
