### ISSUE TITLE
Investigate UPCs

### ISSUE THREAD

**Issue by morganbale** [marcdotson/category-captainship#3]
Look for duplicate UPCs in products master file

**Comment by cdbale** [comment]
The products master file contains a duplicate for a given UPC any time one of the following changes:
   - upc 
   - product_module_code
   - brand
   - size1
   - multipack
There are 145,019 UPC codes with duplicate entries in the products master file. This means that when the products file is merged with a movement file, it results in millions of duplicated observations in the movement file, distorting sales, market share, etc. This is a problem we haven't dealt with yet.

There is a variable which indicates the UPC version (1, 2, etc.) in the products file. We could choose to only use the first version of the UPC. 

My first thought was to merge the products file to the movement file by the UPC and other characteristics that could uniquely identify which UPC version was being sold in the movement file, but the only variable the movement file contains at the UPC level is the UPC code. So, the only way to merge the products and movements files is on UPC.

@jeff-dotson @marcdotson let us know if you can think of a way around this.

**Comment by cdbale** [comment]
Nevermind @jeff-dotson @marcdotson , we figured it out.

**Comment by cdbale** [comment]
We've fixed the issue with the duplicated UPCs, and we've added the solution to the data cleaning files.
