### ISSUE TITLE
Initial Modeling

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#51]
Use synthetic control to estimate basic model estimating treatment effect on log(sales).
Generate a table with retailer/category combinations on each row, with a column for captain, validator, private label, and aggregate of the other manufacturers.

- check out gsynth

@jeff-dotson @marcdotson @morganbale @cdbale

**Comment by morganbale** [comment]
-Make sure nothing kicks in in the post period that would alter the treatment effect (potential cofounders post treatment) → refresh date
-Interpolation bias concern, we want each donor to be close to the treated case
^^look into this and make sure we choose close cases for our treated stores
-Do we have too many time periods relative to units?
-Use placebo test as foundation of inference: take a control and act as though its treated, find treatment effect for that person, do this over and over randomly picking from the controls. We want our effect to be much larger than these placebo effects. (basically what we’ve done in our retailer tests)
@jeff-dotson @marcdotson @cdbale
