### ISSUE TITLE
Begin Modeling

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#56]
- branch out and clean other categories
- input weeks with 0 sales for all upcs
- synthetic control at the store level
- synthetic control is for one treated store and control is an aggregate of non-treated stores
- do it for total category as well as manufacturer level effects
   - 5 total columns: 4 for manufacturers, 1 aggregate (all at the store level)
   - ex: pickles and olives in store1, pickles and olives in store1 for manuf 1, etc.
- use microsynth to get synthetic control values, write a diff-in-diff model ourselves
- restrict bandwidth to 25 weeks before and 25 after (need to find a time frame we can justify)
- as a retailer: care about total category effects, secondary analysis asks, 'who benefits?'
   - within store effects
   - category effects
   - manufacturer effects
   - when does the retailer do their own post implementation analysis of the efficacy of CC?

**Comment by morganbale** [comment]
-Do 26 weeks before & 26 weeks after
-If the volume of sales for the UPCs with two manufacturers is small, just delete. If its large, talk to Jeff
-Make sure the number of weeks is a parameter that is easily changeable, not hard coded
