### ISSUE TITLE
Updating local clones to new main branch

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/category-captainship#77]
@morganbale @cdbale @jeff-dotson @wtrumanrose I've updated the repo to match the latest `repo-template`, including renaming `master` to `main`. You'll need to run the following on your local clones to properly reference the new `main` branch:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by cdbale** [comment]
@marcdotson I'm done with this, feel free to close!
