### ISSUE TITLE
Replicate the horseshoe prior implementation of Bayesian SCM

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/category-captainship#78]
@morganbale @cdbale note that as part of the cleanup I've moved `Model` into `Code`. I know that `Code` is very much in need of a cleaning up at some point. If you can, just move the code you're working on into the root of the `Code` directory with any of the executables and other source files into a folder called `Source` within `Code`.

**Comment by marcdotson** [comment]
@morganbale good job cleaning up the files. I've pulled #81 after cleaning up a few merge conflicts in some of the Stan files. Hopefully I didn't mess anything up? See the closed PR for details on what I changed.

I've also modified the `main` branch by moving your files into `Writing` and removing the figures from `Code`. I went to knit your files and discovered that you named all the code chunks the same. That's like naming all of the files the same -- you'll need a different name for each code chunk for the file to knit and for the figures to have unique names.

I'd recommend creating a new branch to knit and finalize where we're at in terms of the three models: bscm_intercept, bscm_level1, and bscm_testing.

**Comment by marcdotson** [comment]
@morganbale I can take a shot at this now. Good luck to you and Cameron finishing things up for the semester!

**Comment by morganbale** [comment]
@marcdotson sounds good. Thanks! Do you need me to rename the chunks or you will do that as you go through?

**Comment by marcdotson** [comment]
@morganbale I'll take care of it as I go through.

**Comment by marcdotson** [comment]
@morganbale I cleaned it up a bit in the `replicate-bscm` branch:

- I renamed them so I can remember the order: `01_bscm-horseshoe.Rmd`, `02_bscm-intercept.Rmd`, and `03_bscm-levels.Rmd`.
- I was able to knit `01_bscm-horseshoe.Rmd` and `03_bscm-levels.Rmd`, but it looks like there is an issue with the model used in `02_bscm-intercept.Rmd` -- `bscm_b1_intercept.stan`.

Will you take a look at `bscm_b1_intercept.stan`? If you can get it working, go ahead and knit `02_bscm-intercept.Rmd`. Walking through each of these will be a good review when we meet tomorrow.

**Comment by marcdotson** [comment]
Merged with PR #82.
