### ISSUE TITLE
Synthetic Control

### ISSUE THREAD

**Issue by cdbale** [marcdotson/category-captainship#9]
Figure out how to implement synthetic control in our situation. 

Use it to perform the same simple analysis on peanut butter in DC.

Don't care about how we create synthetic control, just want to use one.

Consider ML technique to create synthetic control. 

Start with vanilla synthetic control -- if we get it to work, consider how we can improve construction.

**Comment by cdbale** [comment]
Nice Synthetic Control Documentation

https://www.rdocumentation.org/packages/Synth/versions/0.1-4/topics/synth

**Comment by cdbale** [comment]
Construct synthetic control using weights. (linear combination).
Start documenting synthetic control process.

**Comment by morganbale** [comment]
Put the correct pb dc synth file in github. 

Write a separate R file where we build the synthetic control ourselves. 

Ask @marcdotson about getting graphs to show up when we can't push directly to github.

**Comment by marcdotson** [comment]
You can push graphs to GitHub. I'd recommend creating the graphs as PNG files though. Keep them in the `/Figures` folder.

> `/Figures` Figures created for the README, paper, and presentation, all saves as PNG files.
